name = input("Today you'll get to learn how many vowels and consonants are in the sentence/word you input. Type your word/sentence here: ")
name = name.lower()
count_vowel = len([i for i in name if i in 'aeiou'])
count_consonant = len([i for i in name if i in 'bcdfghjklmnpqrstvwxyz'])
print('Number of vowels in your word/sentence: ' + str(count_vowel) + '.' + ' The number of consonants in your word/sentence: ' +str(count_consonant))